Add Climber Controls to README
RegisJesuitRobotics/Competition2022 pull request #18
Opened 2022-02-19 21:03 UTC by Nins97

2022-02-19 23:00 UTC, ohowe1 requested changes

2022-02-19 23:00 UTC, ohowe1 commented on README.md
> +Configured controls for climbing - Up: dPad up, Down: dPad down, Rotate Forward: dPad right, Rotate Backward: dpad left
```suggestion
## Controls
### Climbing
Up: dPad up
Down: dPad down
Rotate Forward: dPad right
Rotate Backward: dPad left
```
Organization with heading and new lines would be good

2022-02-20 04:59 UTC, ohowe1 reviewed
I messed up the formatting on the last one. Different line for each one now. What do you think

2022-02-20 04:59 UTC, ohowe1 commented on README.md
> +Rotate Backward: dPad left
```suggestion
- Up: dPad up
- Down: dPad down
- Rotate Forward: dPad right
- Rotate Backward: dPad left
```

2022-02-23 00:33 UTC, adambryant approved these changes

2022-03-23 04:44 UTC, closed without merging