Intake Subsystem
RegisJesuitRobotics/Competition2022 pull request #8
Opened 2022-02-10 22:32 UTC by David-rel

2022-02-10 22:33 UTC, ohowe1 requested changes

2022-02-10 22:33 UTC, ohowe1 commented on src/main/java/frc/robot/subsystems/Intake.java
> +  private final Solenoid exampleSolenoidPCM = new Solenoid(PneumaticsModuleType.REVPH, IntakeConstants.SOLENOID_PORT);
You probably want to change this name

2022-02-10 22:45 UTC, ohowe1 requested changes
Some small changes

2022-02-10 22:45 UTC, ohowe1 commented on src/main/java/frc/robot/subsystems/Intake.java
> +
```suggestion
```

You don't need any of these empty functions

2022-02-10 22:45 UTC, ohowe1 commented on src/main/java/frc/robot/subsystems/Intake.java
> +  public void setSolinoid(boolean deployed){
```suggestion
  public void setSolenoid(boolean deployed){
```

2022-02-10 22:48 UTC, ohowe1 approved these changes

2022-02-10 22:48 UTC, ohowe1 commented
Awaiting testing

2022-02-17 23:03 UTC, adambryant approved these changes

2022-02-17 23:04 UTC, merged